### ISSUE TITLE
Include Header displayLanguage 

### ISSUE THREAD

**Issue by ehebel** [aehrc/redcap_advanced_fhir_ontology#1]
I'm trying to make this work with snowstorm but for the Spanish version and I can't manage to find the way to add the "displayLanguage=es" to the request.

**Comment by dconlan** [comment]
I'm really sorry, I don't know why I wasn't notified about this issue. I guess I need to look at my github settings.
Thanks to cpavez for supplying the pull requests.

**Comment by cpavez** [comment]
Don't worry, thanks to you for accepting them, and making this community bigger and stronger. @dconlan

**Comment by dconlan** [comment]
Should I be applying a similar change to redcap_fhir_ontology_provider?

**Comment by cpavez** [comment]
I think so, it would be good

**Comment by dconlan** [comment]
@cpavez 
I've been having a play with using snowstorm and the displayLanguage=es parameter.
I've found it only seems to work when you specify the edition of snomed to use.
i.e. 
https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct/449081005?fhir_vs&displayLanguage=es&filter=asthma&count=10
Will return terms in Spanish, but 
https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs&displayLanguage=es&filter=asthma&count=10
Doesn't return anything

To put the changes into redcap_fhir_ontology_provider I may need to add the snomed edition and possibly version to the configuration so that the searched used to find valueset url will work correctly. So then the question becomes do I allow the displayLanguage/edition/version project specific or make them system level?

**Comment by cpavez** [comment]
I think it's better at the system level. It's strange maybe projects in different languages.El 06-07-2023, a la(s) 00:41, David Conlan ***@***.***> escribió:﻿
@cpavez
I've been having a play with using snowstorm and the displayLanguage=es parameter.
I've found it only seems to work when you specify the edition of snomed to use.
i.e.
https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct/449081005?fhir_vs&displayLanguage=es&filter=asthma&count=10
Will return terms in Spanish, but
https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs&displayLanguage=es&filter=asthma&count=10
Doesn't return anything
To put the changes into redcap_fhir_ontology_provider I may need to add the snomed edition and possibly version to the configuration so that the searched used to find valueset url will work correctly. So then the question becomes do I allow the displayLanguage/edition/version project specific or make them system level?

**Comment by dconlan** [comment]
Since I've done release 0.3 I'll close this issue.
